### PR TITLE
BUGFIX: Exception was being raised when add_to_PATH was not set

### LINKED ISSUE #5: 'NoneType' object is not subscriptable
Just set up `stack` and `stack ide` on new machine, then `stack new --resolver nightly-2015-06-28`, then cloned `stack-ide-sublime` in right folder of ST3, then started sublime, and got:

```
[SublimeStackIDE][ERROR]: 'NoneType' object is not subscriptable
Exception AttributeError: "'StackIDE' object has no attribute 'process'" in <bound method StackIDE.__del__ of <stack-ide-sublime.stack-ide.StackIDE object at 0x1122fb390>> ignored
Switched syntax to SublimeHaskell's fixed Haskell syntax: /Users/rvion/yesodtest/app/Main.hs
```

in terminal, `stack ide` yields:

```
{"tag":"ResponseWelcome","contents":[0,1,0]}
{"tag":"ResponseLog","contents":"[Info] Initializing ide-backend session @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:195:3)\n"}
{"tag":"ResponseLog","contents":"[Debug] Session dir = /Users/rvion/yesodtest/session.74541 @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:208:3)\n"}
{"tag":"ResponseLog","contents":"[Debug] Dist dir = /Users/rvion/yesodtest/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/ @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:210:3)\n"}
{"tag":"ResponseLog","contents":"[Debug] Local working dir = /Users/rvion/yesodtest/ @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:217:17)\n"}
{"tag":"ResponseLog","contents":"[Info] Searching for ide-backend-server on this path: /Users/rvion/yesodtest/.stack-work/install/x86_64-osx/nightly-2015-06-28/7.10.1/bin/:/Users/rvion/.stack/snapshots/x86_64-osx/nightly-2015-06-28/7.10.1/bin/:/Users/rvion/.local/bin/:/Users/rvion/.nix-profile/bin:/Users/rvion/.nix-profile/sbin:/Users/rvion/dev/go/bin:/Users/rvion/dev/Nim/bin/:/Users/rvion/.babel/pkgs/babel-0.4.0:/Users/rvion/.babel/bin/:/Users/rvion/Library/Haskell/bin:/usr/local/heroku/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/go/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:341:5)\n"}
{"tag":"ResponseLog","contents":"[Info] Found ide-backend-server - using this one: /Users/rvion/.local/bin/ide-backend-server @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:343:5)\n"}
{"tag":"ResponseLog","contents":"[Debug] Recompile required, starting... @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update.ExecuteSessionUpdate ./IdeSession/Update/ExecuteSessionUpdate.hs:225:5)\n"}
{"tag":"ResponseLog","contents":"[Info] Restarting session due to update requiring it. @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:422:11)\n"}
{"tag":"ResponseUpdateSession","contents":{"tag":"UpdateStatusRequiredRestart","contents":[]}}
{"tag":"ResponseLog","contents":"[Info] Restarting ide-backend-server @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update ./IdeSession/Update.hs:351:3)\n"}
{"tag":"ResponseLog","contents":"[Info] Searching for ide-backend-server on this path: /Users/rvion/yesodtest/.stack-work/install/x86_64-osx/nightly-2015-06-28/7.10.1/bin/:/Users/rvion/.stack/snapshots/x86_64-osx/nightly-2015-06-28/7.10.1/bin/:/Users/rvion/.local/bin/:/Users/rvion/.nix-profile/bin:/Users/rvion/.nix-profile/sbin:/Users/rvion/dev/go/bin:/Users/rvion/dev/Nim/bin/:/Users/rvion/.babel/pkgs/babel-0.4.0:/Users/rvion/.babel/bin/:/Users/rvion/Library/Haskell/bin:/usr/local/heroku/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/go/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:341:5)\n"}
{"tag":"ResponseLog","contents":"[Info] Found ide-backend-server - using this one: /Users/rvion/.local/bin/ide-backend-server @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:343:5)\n"}
{"tag":"ResponseLog","contents":"[Debug] Recompile required, starting... @(ideba_08u84ABYOFqKEfpIIMNLPr:IdeSession.Update.ExecuteSessionUpdate ./IdeSession/Update/ExecuteSessionUpdate.hs:225:5)\n"}
{"tag":"ResponseUpdateSession","contents":{"tag":"UpdateStatusProgress","contents":{"progressOrigMsg":"[1 of 1] Compiling Lib              ( /Users/rvion/yesodtest/src/Lib.hs, interpreted )","progressStep":1,"progressNumSteps":1,"progressParsedMsg":"Compiling Lib"}}}
{"tag":"ResponseUpdateSession","contents":{"tag":"UpdateStatusDone","contents":[]}}
```

### PR DESCRIPTION
**Pull request by jcpetruzza**
Fixes #5.

We were logging the value of `alt_env['PATH']`  but `alt_env` could be `None`.

I also add better logging of exceptions when creating an instance, to ease diagnosing this kind of errors, and also ensure that the `process` field of a `StackIDE` is always defined (that was the cause of the error shown in `StackIDE.__del__`).

### CODE REVIEW

**Comment by lukexi** [comment]
Hahaha, we fixed it at the same time!

**Comment by lukexi** [comment]
I reverted my commit and grabbed yours since it did a couple other things, thanks : )

**Comment by lukexi** [comment]
Oh, and I added you as a collaborator so feel free to push directly now if you want!

**Comment by jcpetruzza** [comment]
Oh, cool, thanks!

**Pull request merged**
